import type { Metadata } from "next";
import "./globals.css";
import { MantineProvider } from '@mantine/core';
import Navbar from "@/components/Header/Navbar";
import Footer from "@/components/Footer/Footer";
import ErrorBoundary from "@/components/ErrorBoundary";

export const metadata: Metadata = {
  icons: 'uni.png',
  title: "Prague Striking Academy",
  description: "Generated by create next app",
  // other: {
  //   'google-site-verification': 'Vaše-unikátní-řetězec',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <Navbar />
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}